language: bash

os:
  - osx
  # - linux

script:
  - sh ./test.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
