# IMPORTS
source $EISK_HOME/tools/system.eisk
source $EISK_HOME/lib/colors.eisk
source $EISK_HOME/lib/alias.eisk
source $EISK_HOME/lib/git.eisk
source $EISK_HOME/lib/npm.eisk
source $EISK_HOME/lib/rewrite.eisk
source $EISK_HOME/lib/custom.eisk
source $EISK_HOME/tools/rename.eisk
source $EISK_HOME/tools/settings.eisk
