# IMPORTS
source ./tools/system.eisk
source ./lib/colors.eisk
source ./lib/alias.eisk
source ./lib/git.eisk
source ./lib/npm.eisk
source ./lib/rewrite.eisk
source ./lib/custom.eisk
source ./tools/rename.eisk
source ./tools/settings.eisk
